package uwu.smsgamer.senapi.utils;

import javax.script.*;

/**
 * Evaluates shit in python.
 */
public class Evaluator {
    private static final ScriptEngineManager mgr = new ScriptEngineManager();

    /**
     * Returns a new pythonk engine.
     *
     * @return a new pythonk engine.
     */
    public static ScriptEngine newEngine() {
        return mgr.getEngineByName("python");
    }

    /**
     * This documentation's shit and idc. It evaluates a
     * thing in python and returns the return value.
     *
     * @param eval The shit to evaluate.
     * @return the return value of the thing in python.
     * @throws ScriptException if an exception occurred during the processing of the script.
     */
    public static Object evaluate(String eval) throws ScriptException {
        return newEngine().eval(eval);
    }

    /**
     * It evaluates all the extraShit first then evaluates the eval in python and returns the return value.
     *
     * @param eval The shit to evaluate.
     * @param extraShit The extra shit to evaluate. (LOL this piece of doc was generated by an AI)
     * @return the return value of the thing in python.
     * @throws ScriptException if an exception occurred during the processing of the script.
     */
    public static Object evaluateWithParam(String eval, String... extraShit) throws ScriptException {
        ScriptEngine eng = newEngine();
        for (String s : extraShit) eng.eval(s);
        return eng.eval(eval);
    }
}
